language: java

jdk:
  - oraclejdk8

env:
  global:
    - CASSANDRA_VERSION=3.10
  matrix:
    - PROFILE=ci
    - PROFILE=spring5-next
    - CASSANDRA_VERSION=2.2.8
    - CASSANDRA_VERSION=3.0.10
    - CASSANDRA_VERSION=3.2.1
    - CASSANDRA_VERSION=3.9

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2
    - 'download'

sudo: required

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

install: if [ ! -z ${CASSANDRA_VERSION+x} ]; then ./setup-cassandra.sh; fi;

script:
  - |
    if [ ! -z ${CASSANDRA_DRIVER_VERSION+x} ]; then
      mvn clean install -P${PROFILE},external-cassandra -Dcassandra-driver.version=${CASSANDRA_DRIVER_VERSION} -Dmaven.javadoc.skip=true
    else
      mvn clean install -P${PROFILE},external-cassandra -Dmaven.javadoc.skip=true
    fi
