language: java

env:
  global:
    - CASSANDRA_VERSION=3.11.2
  matrix:
    - CASSANDRA_VERSION=2.2.10
    - CASSANDRA_VERSION=3.0.10

cache:
  directories:
    - $HOME/.m2

sudo: false

services:
  - docker

install: true

script: ./mvnw clean install -Pci,testcontainers-cassandra,java11 -Dmaven.javadoc.skip=true -B
